### ISSUE TITLE
Merge different chroms stats into one graph

### ISSUE THREAD

**Issue by baozg** [marschall-lab/panacus#7]
Hi,

How do we merge stats from all chromosomes into a single plot?

Best regards
Zhigui

**Comment by danydoerr** [comment]
This is possible from coverage histogram data, i.e,  the output of `panacus hist ...`, but requires you to manually merge the chromosome data together. This is simple, because they're just tables, and here is one way to do that with python/pandas:

```python
import pandas as pd

FILES=['/your/list/of/chromosomes/chr1.hist.txt', '/your/list/of/chromosomes/chr2.hist.txt', ]
df = None

for f in FILES:
    _df = pd.read_csv(f, sep='\t', header=[1], index_col=[0])
    if df is None:
        df = _df
    else:
        df += _df

with open('/your/output/file.hist.txt') as out:
    df.reset_index().to_csv(out, sep='\t', index=False)
```

Then pass the output file  to panacus, i.e., `panacus growth /your/output/file.hist.txt` and you're good to go.

**Comment by baozg** [comment]
After `panacus hist` and `panacus growth`, the final visualization will show `#nodes` instead of `bps`. I use `-c bp` for hist

**Comment by danydoerr** [comment]
﻿Right, this is a known bug that I need to fix at some point. For the record, it’s just the label that is wrong (good that put this in the ticket here)On 8. Aug 2023, at 22:03, Zhigui Bao ***@***.***> wrote:﻿
After panacus hist and panacus growth, the final visualization will show #nodes instead of bps. I use -c bp for hist

**Comment by jp-jong** [comment]
Hi! I'm just wondering whether combining all og graphs using odgi squeeze, convert to gfa format using odgi view, and finally use panacus ordered-histgrowth is an alternative to this method with the usage of a python script? If not, what are probable errors to this?

**Comment by heringerp** [comment]
Yes, using odgi to merge all chromosomal graphs into a single file is also an alternative to this.
